version: "3.9"

services:
  aniemilia:
    build: .
    image: aniemilia:${TAG}
    container_name: aniemilia
    network_mode: host
    pull_policy: never

networks:
  default: 
    external: true
    name: host